name: Workflow zero
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: step-zero
        name: workflow-test
        run: |
          echo "Hello Judy! $(date)"
      - id: step-one
        name: workflow-test-2
        run: echo "Second step"
      - id: firstStep
        name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "World"
        run: |
          echo "Second Step"
